---
# tasks file for sonar

- name: Ensure Sonar role path is available
  file:
    path: "{{ sonar_path }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - init

- name: Ensure Sonar data volume path is available
  file:
    path: "{{ sonar_data_path }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - init

- name: Ensure Sonar plugins volume path is available
  file:
    path: "{{ sonar_plugins_path }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - init
    